
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/data/data/com.termux/files/usr/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Android - 5.10.136-android12-9-25884040-abX700XXU3BWC1 - aarch64
...
